### ISSUE TITLE
[Suggestion/Request] Disable timed NG+ Mechanics

### ISSUE THREAD

**Issue by ZeekDaGeek** [wobatt/RogueLegacy2Mods#1]
I'm not sure if it would be possible to make as a mod, but I figured I would give it a shot.

The thread options for changing up zones to add tougher enemies are very desirable, however a few of them have mechanics which just boil down to "Don't play the game, instead wait for cannons/big shadow bars/a parade to pass" etc.

It want to enable these thread options because the increased monster variety is great, but the annoying waiting and do nothing mechanics kind of sucks.

**Comment by wobatt** [comment]
I have already done this, released yesterday - [https://www.nexusmods.com/roguelegacy2/mods/27](https://www.nexusmods.com/roguelegacy2/mods/27)

The tougher biome burdens are split into 2 levels. The first level is the enemy spawn changes, the second is the environmental hazards. This allows you to enable only the first level and not the second.

**Comment by ZeekDaGeek** [comment]
That's great! I've been looking around at your mods for the last couple of days and I only looked at the bullet points, I just glanced right past it by mistake before submitting a suggestion. Sorry about that.

Looks like a really good implementation as well.
