### ISSUE TITLE
[Suggestion/Request] Disable fog layers

### ISSUE THREAD

**Issue by ZeekDaGeek** [wobatt/RogueLegacy2Mods#2]
For the accessibility pack:

The ability to disable the fog layer in the Plateau would probably be a nice feature that other people would want.

I was able to disable it by modifying the `ForestFog -> "m_isActive": false` in `assets/content/prefabs/fx/weather_forestfog.prefab` `(Path ID: 6141201777075177162)` however I have no idea how to package everything up nicely as an actual mod, and I just replaced the whole `prefab` file in my install.

The main reason I needed to do this was the fog layer causing visibility issues on my monitor, the white was just blowing everything out and making it harder to see.

Sorry for bothering you with suggestions through github. 💙

Edit: there's also a Fog layer for the Cave, but it's not as visually bad.

**Comment by wobatt** [comment]
Thanks for the suggestion. Could you provide some screenshots, before and after your change, so I can see what I am aiming for?
My method for creating mods is to affect the code rather than the asset, so I will need to find where the asset is loaded by the code and disable it there.

**Comment by ZeekDaGeek** [comment]
Here's a screenshot of the vanilla fog:
![C2Y94](https://user-images.githubusercontent.com/1709288/175114747-455c6f78-adf7-4c55-8bd3-b2d0ba5503c7.png)

Here's without fog:
![KByrZ](https://user-images.githubusercontent.com/1709288/175114789-6be712c3-de98-4e1d-a7b6-08ef2a9b91ec.png)

I honestly forgot how bad it was until turning it back on. It's everywhere!
![18XFO](https://user-images.githubusercontent.com/1709288/175114939-f2168211-2a04-429d-80e8-77214f80c7cd.png)

![lKyXg](https://user-images.githubusercontent.com/1709288/175115837-537ad76b-069b-4c73-a425-6994e366f921.png)


If you want to try it yourself here's the replacement `prefab`, unfortunately Asset Bundle Extractor doesn't compress it as well as the RL2 devs did so the files a lot larger.

Just replace `Rogue Legacy 2\Rogue Legacy 2_Data\StreamingAssets\AssetBundles\prefabs` after backing up your original.
https://zeekdageek.tv/mods/roguelegacy2/

**Comment by wobatt** [comment]
Thanks. Mod updated: [https://www.nexusmods.com/roguelegacy2/mods/7](https://www.nexusmods.com/roguelegacy2/mods/7)

It prevents all fog/mist effects in the game from being displayed, not just Kerguelen Plateau.
